# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'My_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import matplotlib

matplotlib.use("Qt5Agg")
from PyQt5.QtWidgets import QSizePolicy, QWidget, QVBoxLayout
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5 import NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure


class MplCanvas(FigureCanvas):

    def __init__(self, dpi=100):
        self.fig = Figure(dpi=dpi)
        self.axes = self.fig.add_subplot(111, projection='3d')
        FigureCanvas.__init__(self, self.fig)

class MPL_WIDGET_2D(QWidget):

    def __init__(self, parent=None):
        QWidget.__init__(self, parent)
        self.canvas = MplCanvas()  # create canvas that will hold our plot
        self.navi_toolbar = NavigationToolbar(self.canvas, self)  # createa navigation toolbar for our plot canvas

        self.vbl = QVBoxLayout()
        self.vbl.addWidget(self.canvas)
        self.vbl.addWidget(self.navi_toolbar)
        self.setLayout(self.vbl)


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 664)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mplwidget2D = MPL_WIDGET_2D(self.centralWidget)
        self.mplwidget2D.setObjectName("mplwidget2D")
        self.horizontalLayout.addWidget(self.mplwidget2D)
        MainWindow.setCentralWidget(self.centralWidget)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.dockWidgetContents_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_lam = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_lam.setObjectName("label_lam")
        self.verticalLayout.addWidget(self.label_lam)
        self.SpinBox_lam = QtWidgets.QSpinBox(self.dockWidgetContents_3)
        self.SpinBox_lam.setMinimum(400)
        self.SpinBox_lam.setMaximum(900)
        self.SpinBox_lam.setSingleStep(10)
        self.SpinBox_lam.setProperty("value", 560)
        self.SpinBox_lam.setObjectName("SpinBox_lam")
        self.verticalLayout.addWidget(self.SpinBox_lam)
        self.slider_lam = QtWidgets.QSlider(self.dockWidgetContents_3)
        self.slider_lam.setMinimum(400)
        self.slider_lam.setMaximum(900)
        self.slider_lam.setSingleStep(10)
        self.slider_lam.setProperty("value", 560)
        self.slider_lam.setOrientation(QtCore.Qt.Horizontal)
        self.slider_lam.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_lam.setTickInterval(50)
        self.slider_lam.setObjectName("slider_lam")
        self.verticalLayout.addWidget(self.slider_lam)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_scale_1 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_scale_1.setObjectName("label_scale_1")
        self.verticalLayout.addWidget(self.label_scale_1)
        self.SpinBox_scale_1 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents_3)
        self.SpinBox_scale_1.setDecimals(1)
        self.SpinBox_scale_1.setMinimum(0.1)
        self.SpinBox_scale_1.setMaximum(1.0)
        self.SpinBox_scale_1.setSingleStep(1.0)
        self.SpinBox_scale_1.setProperty("value", 0.5)
        self.SpinBox_scale_1.setObjectName("SpinBox_scale_1")
        self.verticalLayout.addWidget(self.SpinBox_scale_1)
        self.slider_scale_1 = QtWidgets.QSlider(self.dockWidgetContents_3)
        self.slider_scale_1.setMinimum(1)
        self.slider_scale_1.setMaximum(10)
        self.slider_scale_1.setProperty("value", 5)
        self.slider_scale_1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_scale_1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_scale_1.setTickInterval(10)
        self.slider_scale_1.setObjectName("slider_scale_1")
        self.verticalLayout.addWidget(self.slider_scale_1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_scale_2 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_scale_2.setObjectName("label_scale_2")
        self.verticalLayout.addWidget(self.label_scale_2)
        self.SpinBox_scale_2 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents_3)
        self.SpinBox_scale_2.setDecimals(1)
        self.SpinBox_scale_2.setMinimum(0.1)
        self.SpinBox_scale_2.setMaximum(1.0)
        self.SpinBox_scale_2.setProperty("value", 0.5)
        self.SpinBox_scale_2.setObjectName("SpinBox_scale_2")
        self.verticalLayout.addWidget(self.SpinBox_scale_2)
        self.slider_scale_2 = QtWidgets.QSlider(self.dockWidgetContents_3)
        self.slider_scale_2.setMinimum(1)
        self.slider_scale_2.setMaximum(10)
        self.slider_scale_2.setProperty("value", 5)
        self.slider_scale_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_scale_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_scale_2.setTickInterval(10)
        self.slider_scale_2.setObjectName("slider_scale_2")
        self.verticalLayout.addWidget(self.slider_scale_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_hole = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_hole.setObjectName("label_hole")
        self.verticalLayout.addWidget(self.label_hole)
        self.comboBox_hole_name = QtWidgets.QComboBox(self.dockWidgetContents_3)
        self.comboBox_hole_name.setObjectName("comboBox_hole_name")
        self.comboBox_hole_name.addItem("")
        self.comboBox_hole_name.addItem("")
        self.verticalLayout.addWidget(self.comboBox_hole_name)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.label_z = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_z.setObjectName("label_z")
        self.verticalLayout.addWidget(self.label_z)
        self.SpinBox_z = QtWidgets.QDoubleSpinBox(self.dockWidgetContents_3)
        self.SpinBox_z.setDecimals(1)
        self.SpinBox_z.setMinimum(10.0)
        self.SpinBox_z.setMaximum(20.0)
        self.SpinBox_z.setProperty("value", 2.0)
        self.SpinBox_z.setObjectName("SpinBox_z")
        self.verticalLayout.addWidget(self.SpinBox_z)
        self.slider_z = QtWidgets.QSlider(self.dockWidgetContents_3)
        self.slider_z.setMinimum(10)
        self.slider_z.setMaximum(20)
        self.slider_z.setProperty("value", 15)
        self.slider_z.setOrientation(QtCore.Qt.Horizontal)
        self.slider_z.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_z.setTickInterval(10)
        self.slider_z.setObjectName("slider_z")
        self.verticalLayout.addWidget(self.slider_z)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.dockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 855, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Diffraction  Rectangular aperture"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Setting"))
        self.label_lam.setText(_translate("MainWindow", "Wave length(nm)"))
        self.SpinBox_lam.setStatusTip(_translate("MainWindow", "Change the wave length of monochromatic light"))
        self.slider_lam.setStatusTip(_translate("MainWindow", "Change the wave length of monochromatic light"))
        self.label_scale_1.setText(_translate("MainWindow", "scale1(0.1mm)"))
        self.SpinBox_scale_1.setStatusTip(_translate("MainWindow", "Change the width of the rectangular aperture"))
        self.slider_scale_1.setStatusTip(_translate("MainWindow", "Change the width of the rectangular aperture"))
        self.label_scale_2.setText(_translate("MainWindow", "scale2(0.1mm)"))
        self.SpinBox_scale_2.setStatusTip(_translate("MainWindow", "change the height of the recatangular aperture"))
        self.slider_scale_2.setStatusTip(_translate("MainWindow", "change the height of the recatangular aperture"))
        self.label_hole.setText(_translate("MainWindow", "hole shape"))
        self.comboBox_hole_name.setItemText(0, _translate("MainWindow", "rectangle"))
        self.comboBox_hole_name.setItemText(1, _translate("MainWindow", "round"))
        self.label_z.setText(_translate("MainWindow", "z(m)"))
        self.SpinBox_z.setStatusTip(_translate("MainWindow", "Change the focal length f2 of the lens L2"))
        self.slider_z.setStatusTip(_translate("MainWindow", "Change the focal length f2 of the lens L2"))
